version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

  app-timesheet:
    image: chaima622/tpfoyer-image:1.0.0        # ou build: .  si tu rebuilds localement
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: |-
        {
          "spring.datasource.url"            : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC",
          "spring.datasource.username"       : "root",
          "spring.datasource.password"       : "root",
          "spring.jpa.database-platform"     : "org.hibernate.dialect.MySQL5Dialect",
          "spring.jpa.hibernate.ddl-auto"    : "update",
          "spring.jpa.show-sql"              : "true"
        }
    stdin_open: true
    tty: true

volumes:
  db:
